-- Performance indexes for common query patterns
-- Generated by API performance audit on 2026-03-08

-- orders table: queries filter by order_ref, stripe_session_id, printify_order_id,
-- customer_email. order_ref already has UNIQUE (implies btree index), but
-- stripe_session_id and customer_email benefit from explicit indexes.
-- stripe_session_id is UNIQUE in the initial schema but gains a partial index
-- for clarity and to cover nullable future states.

CREATE INDEX IF NOT EXISTS idx_orders_order_ref
  ON public.orders(order_ref);

CREATE INDEX IF NOT EXISTS idx_orders_printify_order_id
  ON public.orders(printify_order_id)
  WHERE printify_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_stripe_session_id
  ON public.orders(stripe_session_id)
  WHERE stripe_session_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_customer_email
  ON public.orders(customer_email)
  WHERE customer_email IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_status
  ON public.orders(status);

-- order_items: always joined via order_ref
CREATE INDEX IF NOT EXISTS idx_order_items_order_ref
  ON public.order_items(order_ref);

-- subscribers: looked up by email to check for duplicates before upsert
CREATE INDEX IF NOT EXISTS idx_subscribers_email
  ON public.subscribers(email);

-- stripe_events: idempotency check filters by stripe_event_id (already UNIQUE,
-- which implicitly creates a btree index, so no extra index needed here).

-- daily_usage: primary key is (user_key, day_key) so no extra index needed.
-- user_profiles: primary key is user_key so no extra index needed.
